import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
      // Will be passed to the page component as props
    },
  };
}

export default function Home() {
  const { t } = useTranslation("common");

  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS Localization Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("site-title")}</h1>
        <p className={styles.description}>{t("site-description")}</p>

        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>{t("feature1-title")} &rarr;</h2>
            <p>{t("feature1-description")}</p>
          </a>

          <a href="" className={styles.card}>
            <h2>{t("feature2-title")} &rarr;</h2>
            <p>{t("feature2-description")}</p>
          </a>

          <a href="" className={styles.card}>
            <h2>{t("feature3-title")} &rarr;</h2>
            <p>{t("feature3-description")}</p>
          </a>

          <a href="" className={styles.card}>
            <h2>{t("feature4-title")} &rarr;</h2>
            <p>{t("feature4-description")}</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="" target="_blank" rel="noopener noreferrer">
          _
        </a>
      </footer>
    </div>
  );
}
