import axios from "axios";
import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Link from "next/link";
import { LocaleSwitcher } from "../components/LanguageSwitcher";

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
      // Will be passed to the page component as props
    },
  };
}

export default function Home({ data }) {
  const { t } = useTranslation("common");
  const [currentLanguages, setcurrentLanguages] = useState([]);

  useEffect(() => {
    const getData = async () => {
      const {
        data: {
          data: { targetLanguages },
        },
      } = await axios.get(
        // "api/crowdin/" + "projects/2/languages/mr/translations"
        "api/crowdin/" + "projects/2"
      );
      setcurrentLanguages(targetLanguages);
    };
    getData();
  }, []);

  return (
    <>
      <div
        style={{
          display: "flex",
          marginTop: "1rem",
          paddingRight: "1rem",
          alignItems: "center",
          justifyContent: "flex-end",
          gap: "2rem",
        }}
      >
        <ul
          style={{
            display: "flex",
            gap: "0.5rem",
            listStyle: "none",
            alignItems: "center",
          }}
        >
          <li>
            <Link href="/">
              <a>Home</a>
            </Link>
          </li>
          <li>
            <Link href="/about">
              <a>About Us</a>
            </Link>
          </li>
          <li>
            <Link href="/blog/hello-world">
              <a>Blog</a>
            </Link>
          </li>
        </ul>
        <LocaleSwitcher options={currentLanguages} />
      </div>

      <div className={styles.container}>
        <Head>
          <title>Next JS Localization Demo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>{t("site-title")}</h1>
          <p className={styles.description}>{t("site-description")}</p>

          <div className={styles.grid}>
            <a href="" className={styles.card}>
              <h2>{t("feature1-title")} &rarr;</h2>
              <p>{t("feature1-description")}</p>
            </a>

            <a href="" className={styles.card}>
              <h2>{t("feature2-title")} &rarr;</h2>
              <p>{t("feature2-description")}</p>
            </a>

            <a href="" className={styles.card}>
              <h2>{t("feature3-title")} &rarr;</h2>
              <p>{t("feature3-description")}</p>
            </a>

            <a href="" className={styles.card}>
              <h2>{t("feature4-title")} &rarr;</h2>
              <p>{t("feature4-description")}</p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a href="" target="_blank" rel="noopener noreferrer">
            _
          </a>
        </footer>
      </div>
    </>
  );
}
